### ISSUE TITLE
Consider using the new "File System Access API" in Chrome as a progressive enhancement

### ISSUE THREAD

**Issue by blake-mealey** [Apicurio/apicurito#114]
Hey, have you considered the new [File System Access API](https://web.dev/file-system-access/) in Chrome?

It could be used as a progressive enhancement when available to offer users a better file reading/saving experience. Currently when the user clicks save, the file is downloaded to their Downloads folder. With this feature, the user could save it back to the file they originally imported.

I'm not sure whether this would be a change to this project or the Apicurio project, so please redirect me to the appropriate project if required.

I would be interested in attempting a PR if you're interested in this.

**Comment by EricWittmann** [comment]
Yes this would be very interesting.  The change would definitely go in the Apicurito project.  Let me know if you need a pointer to the right place in the code to get started.  Thanks!

**Comment by blake-mealey** [comment]
Cool, I'll give it a shot tomorrow. From a quick search through the code I think I have a general idea of where the relevant bits are. I'll let  you know if I need any help

**Comment by schelv** [comment]
Nice feature would it also be possible to use this with some kind of autosave function?

**Comment by EricWittmann** [comment]
Oops this should have been closed.

@schelv Can you open a new issue with your request?
