### ISSUE TITLE
Consider wrapping Apicurito in a lightweight native app?

### ISSUE THREAD

**Issue by blake-mealey** [Apicurio/apicurito#116]
Do you have an interest in wrapping the project in a lightweight native app? Electron seems overkill since you don't actually need any native features (except maybe improved FS support).

It just seems like the intended workflow for this product is to run it locally as an app, and having it wrapped as a standalone Windows app would be nicer than running the docker container and opening a browser tab to localhost.

From some quick Googling I found [NeutralinoJs](https://neutralino.js.org/docs/#/) which could work for this.

**Comment by EricWittmann** [comment]
This is an interesting idea.  And I see why you have the sense that the intended workflow is running as a local app.  The short answer here is I think it would be a wonderful thing!

The longer answer is that the driving force behind Apicurito is to have a stripped down version of Apicurio Studio without a back-end to make it easier to include in Red Hat products (without the difficulty of productizing all of Apicurio Studio).  That's the rationale, but I guess it's a distinction without a real practical difference.  The bottom line is that the resulting **workflow** for users is very much a "desktop application" flow.

So I guess what I'm saying is this:  for the Apicurio upstream community, I would *love* to see a "native" app for Apicurito.  It would make much more sense why we have it.

**Comment by blake-mealey** [comment]
Another option for this which would be significantly simpler to implement would be to make Apicurito a PWA so that it could be installed through a modern browser. The only issue with that is it would need to be hosted somewhere for it to be downloadable.

If it was a PWA, I could host it on an internal website at my company and it would solve my needs.

Do you think Red Hat would consider hosting it publically (it would still just be a frontend static site so costs could be pretty minimal).

**Comment by EricWittmann** [comment]
I don't have much experience with progressive web apps - can you give a quick summary of the packaging and hosting requirements?  Or a link if there is a good summary on this topic.

Depending on the requirements, maybe it can just be hosted on https://apicur.io

**Comment by blake-mealey** [comment]
So for the purposes of Apicurito, we would build the Angular web app, producing the static website (HTML, CSS, and JS files), then host these on a webserver.

All that is required to make it a PWA is:

* A manifest file - an additional static JSON file which provides app metadata like name, short name, icon URLs, theme colour
* A service worker, which would be implemented in two "parts"
  * Some new Angular code which tells the browser to load the SW and a few other things
  * A new static JS file which is the service worker. I would use [workbox](https://developers.google.com/web/tools/workbox) to generate this file

Then basically the way the PWA works is:

1. User navigates to website in their browser
2. Browser downloads the website
3. JS code tells the browser to register the SW
4. Once the SW is registered, all requests for the static sites pass through the SW first, which maintains a custom cache
5. Now the user can access the website without having an internet connection since all the files will be available through the SW cache
6. The user can now click on the browser's Install button to install the app to their computer and it will appear in their apps list

Most of the complexity is in implementing the SW, but there's no need to actually do that manually because workbox can be used to generate it automatically based on desired caching algorithms, etc.

**Comment by EricWittmann** [comment]
This all sounds very straightforward.  I can't see why it couldn't be hosted on a GitHub Pages site.

**Comment by blake-mealey** [comment]
Come to think of it, yes there's absolutely no reason that wouldn't work!

**Comment by blake-mealey** [comment]
I'll take a stab at a PR for making the app a PWA
