### ISSUE TITLE
Can we integrate it in existing Angular application?

### ISSUE THREAD

**Issue by hardythaker** [Apicurio/apicurito#123]
I was trying to integrate in my existing Angular 11 application. But build got failed due to ngx-bootstarp 3.0.2 is not working in Angular11. 

```
An unhandled exception occurred: The target entry-point "ngx-bootstrap" has missing dependencies:
 - @angular/forms/src/directives/control_value_accessor
 - @angular/core/src/type
```

And if I upgrade the ngx-bootstrap package to latest version then apicurio-design-studio package failed to build.

```
Error: node_modules/apicurio-design-studio/app/common-components.module.d.ts:28:26 - error TS2307: Cannot find module 'ngx-bootstrap' or its corresponding type declarations.

28 import * as ɵngcc11 from 'ngx-bootstrap';
```

**Comment by EricWittmann** [comment]
I'm afraid to say that you are probably on your own for this one.  We would probably need to upgrade Studio to Angular 11 for this to work.  I'm very uncomfortable trying to resolve mismatched dependencies in the javascript world, unfortunately. 

If you wanted to take a stab at upgrading Studio to Angular 11, I'd be happy to try and help resolve issues you run into.  Sadly that's the best I can offer.

**Comment by assimbly** [comment]
I also like to integrate Apicurio / Apicurito in my Angular application. @hardythaker / @EricWittmann  is there a guide or steps to take to achieve this. For example is there a npm package.

**Comment by EricWittmann** [comment]
The NPM package is here:

https://www.npmjs.com/package/apicurio-design-studio

The best I can do for this is to direct you to Apicurito, which itself embeds the OpenAPI editor component found in the above NPM library.  The source for Apicurito is here:

https://github.com/apicurio/apicurito

Note the dependency on the NPM package here:

https://github.com/Apicurio/apicurito/blob/master/ui/package.json#L26

Usage of the OpenAPI editor can be found here:

https://github.com/Apicurio/apicurito/blob/master/ui/src/app/editor/editor.component.html#L48-L50

Note: You'll also need the apicurio-data-models NPM package.
Note: The editor component is originally developed as part of the Apicurio Studio project and exported as a shared component.

**Comment by EricWittmann** [comment]
Let me know if that helps or if you have more specific questions!

**Comment by assimbly** [comment]
Hi Eric, thanks for your answer, exactly what i was looking for.
