### ISSUE TITLE
archive this repository?

### ISSUE THREAD

**Issue by gashcrumb** [Apicurio/apicurito#137]
I saw from [this comment](https://github.com/Apicurio/apicurito/issues/136#issuecomment-911548365) that this operator is now developed from https://github.com/Apicurio/apicurio-operators/tree/master/apicurito, should this repo be archived or marked deprecated?

**Comment by EricWittmann** [comment]
This repository is the Apicurito app itself *and* an old operator for it.  We can remove the operator code from the repo (good idea) but cannot archive the entire repo.

**Comment by gashcrumb** [comment]
Yeah it'd probably be good to remove the operator code if it's out of date.  Thanks for clarifying!

**Comment by EricWittmann** [comment]
What do you think @phantomjinx - can/should we delete the operator in this repo?

**Comment by phantomjinx** [comment]
> What do you think @phantomjinx - can/should we delete the operator in this repo?

Yes. Makes sense.

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurito/pull/138
