### ISSUE TITLE
Importing a YAML files

### ISSUE THREAD

**Issue by Cediddi** [Apicurio/apicurito#23]
Standard Apicurio Studio supports importing yaml files. This project utilizes bot yamljs and js-yaml.

yamljs supports loading with a simple api. `var doc = YAML.parse(yamlString);`
js-yaml also supports loading with an api `var doc = yaml.safeLoad(yamlString);`

Both options look good but which library does apicurito mainly use or prefer?

I believe this is an easy fix. I think I may tackle this issue with a PR. It looks easy.

**Comment by EricWittmann** [comment]
The library we've been using mainly is `yamljs` - any other yaml libraries must be getting pulled in transitively.

I'd love a PR - that'd be very helpful, thanks.

**Comment by EricWittmann** [comment]
By the way - it seems that `yamljs` is already being included in `package.json` - so this should just be a matter of adding the bit of code to do the `YAML.parse()` as you've indicated above.  :)  I hope!

**Comment by Cediddi** [comment]
Well, merge is done, so I'm closing this issue.

**Comment by EricWittmann** [comment]
Only reason I hadn't closed it yet is that I haven't had a chance to test this yet.  :)

**Comment by Cediddi** [comment]
Sorry, my bad. It worked on my computer :stuck_out_tongue:

**Comment by EricWittmann** [comment]
Oh no - I'm sure it works fine, I just haven't verified it yet!  I'll test it right now. :)

**Comment by EricWittmann** [comment]
Works great, thanks for the contribution.  Only one small change was needed, but fixed in this commit:

https://github.com/Apicurio/apicurito/commit/02b5dfbea41466ce74e6d3ae153a35fe70f84826

Minor issue about the error message when failing to parse a YAML file.
