### ISSUE TITLE
Operator: How to specify the namespace without hardcoding it in the image?

### ISSUE THREAD

**Issue by avano** [Apicurio/apicurito#36]
From the operator readme it seems it is not possible to specify the namespace other way than hardcoding it in the image's `values.yaml` file.

Is there a way how to modify it via some variable?

Currently in the productized image there is `ns-apicurito` namespace hardcoded, whereas I would expect I can specify my namespace somewhere

cc @heiko-braun @lgarciaaco @mmajerni

**Comment by heiko-braun** [comment]
//cc @nicolaferraro @astefanutti  Any ideas?

**Comment by lgarciaaco** [comment]
If I am not mistaken the `namespace` parameter is required when creating a Role https://github.com/Apicurio/apicurito/blob/master/operator/deploy/rbac.yaml#L1, so answer is no, but I will give it a try removing the `namespace: REPLACE_NAMESPACE` and hope it works.

**Comment by avano** [comment]
@lgarciaaco the `rbac.yaml` is ok as that is not in the image, I was worried about `values.yaml` that is directly in the image and from what I understood from the brief look, it defines where the is/dc will be created.. is that right?

**Comment by lgarciaaco** [comment]
Let me check that ...

**Comment by lgarciaaco** [comment]
@avano after merging, rebuilding the operator image is optional. The operator image would still contain the old `values.yaml` with the namespace variable in it, but it is not used.
