### ISSUE TITLE
Small issue with Data Types and undo/redo

### ISSUE THREAD

**Issue by mmajerni** [Apicurio/apicurito#38]
Steps to reproduce:

- Create 3 data types e. g. "d1", "d2", "d3".
- Click 3 times on undo button. (There is no data type now)
- Click 3 times on redo button. (All 3 data types should appear again)

But first one (d1 in our case) does not appear.

- Again click 2 times on undo and after that 2 times on redo. Again first data type (d2 in our case) is not available.

**Comment by EricWittmann** [comment]
I believe this has been fixed with the most recent release.
