### ISSUE TITLE
Responses validation check missing

### ISSUE THREAD

**Issue by mmajerni** [Apicurio/apicurito#72]
Issue Type: Major
Version: Nov 6, 2019 (1.1.1)

When Response is created from Response Definition (RD) there is not a validation check. 

Steps to reproduce:
- Create responses without and with RD.

The response created without RD shows validation problem (empty description)
The response created with RD show no validation problem

**Comment by EricWittmann** [comment]
You don't need a description if you are using a response definition.

**Comment by EricWittmann** [comment]
Oh but I see your point - a Response Definition **does** require a description and we don't catch that in the validation.

**Comment by EricWittmann** [comment]
https://github.com/Apicurio/apicurio-data-models/issues/88
