### ISSUE TITLE
API cannot be edited after converting API to OpenAPI 3 

### ISSUE THREAD

**Issue by mmajerni** [Apicurio/apicurito#90]
Apicurito version: 1.2.1

Steps to reproduce: 

- Create API with OpenAPI 2 
- Create one path
- Click on the Convert button
- Create another path or do some other action (it is not possible)

After export and import API, editor again work as is expected.

**Comment by EricWittmann** [comment]
I believe this to actually be a bug in the upstream (Apicurio Studio) editor component.  I have opened an issue there:  https://github.com/Apicurio/apicurio-studio/issues/1031

However, I will try to create a workaround in Apicurito that doesn't require that bug to be fixed.  Then later I'll come back around and fix the core issue, upgrade to the latest editor in Apicurito, and remove the workaround.
